{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: logspray-server
  labels:
    app: logspray-server
spec:
  type: LoadBalancer
  ports:
  - port: 10000
    protocol: TCP
    name: grpc
  selector:
    app: logspray-server
{{end}}
