{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: logspray-reader
  labels:
    app: logspray-reader
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9998
    protocol: TCP
  selector:
    app: logspray-reader
  type: ClusterIP
{{end}}
